# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xml_generator_front.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 680)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/file_xml-512.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_20.addWidget(self.widget_2, 2, 0, 1, 1)
        self.widget_header = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_header.sizePolicy().hasHeightForWidth())
        self.widget_header.setSizePolicy(sizePolicy)
        self.widget_header.setAutoFillBackground(False)
        self.widget_header.setObjectName("widget_header")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_header)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_39 = QtWidgets.QLabel(self.widget_header)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout_2.addWidget(self.label_39, 0, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.widget_header)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout_2.addWidget(self.label_40, 0, 1, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.widget_header)
        self.spinBox_3.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spinBox_3.setMinimum(1)
        self.spinBox_3.setMaximum(500000)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_2.addWidget(self.spinBox_3, 1, 0, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.widget_header)
        self.spinBox_4.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.spinBox_4.setFont(font)
        self.spinBox_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spinBox_4.setMinimum(1)
        self.spinBox_4.setMaximum(5000)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_2.addWidget(self.spinBox_4, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget_header)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 2, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.widget_header)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.gridLayout_2.addWidget(self.label_41, 2, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.widget_header)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.gridLayout_2.addWidget(self.label_42, 2, 1, 1, 1)
        self.gridLayout_20.addWidget(self.widget_header, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButton_4)
        self.gridLayout_3.addWidget(self.radioButton_4, 5, 0, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_25.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_25.setFont(font)
        self.lineEdit_25.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_25.setMaxLength(64)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_3.addWidget(self.lineEdit_25, 5, 3, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_27.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_27.setFont(font)
        self.lineEdit_27.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_27.setMaxLength(64)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_3.addWidget(self.lineEdit_27, 5, 2, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_5.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup_2.addButton(self.radioButton_5)
        self.gridLayout_3.addWidget(self.radioButton_5, 6, 0, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_26.setEnabled(False)
        self.lineEdit_26.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_26.setFont(font)
        self.lineEdit_26.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_26.setMaxLength(64)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_3.addWidget(self.lineEdit_26, 6, 3, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_4.setMaxLength(256)
        self.lineEdit_4.setClearButtonEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 3, 1, 1, 3)
        self.spinBox = QtWidgets.QSpinBox(self.tab)
        self.spinBox.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.spinBox.setFont(font)
        self.spinBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spinBox.setWrapping(False)
        self.spinBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.spinBox.setSuffix("")
        self.spinBox.setPrefix("")
        self.spinBox.setMinimum(1900)
        self.spinBox.setMaximum(2200)
        self.spinBox.setProperty("value", 1900)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_3.addWidget(self.spinBox, 4, 1, 1, 3)
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_3.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_3)
        self.gridLayout_3.addWidget(self.radioButton_3, 2, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_5.setMaxLength(64)
        self.lineEdit_5.setClearButtonEnabled(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 4, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_6.setMaxLength(64)
        self.lineEdit_6.setClearButtonEnabled(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_3.addWidget(self.lineEdit_6, 6, 1, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup.addButton(self.radioButton)
        self.gridLayout_3.addWidget(self.radioButton, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_3.setMaxLength(32)
        self.lineEdit_3.setClearButtonEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 2, 1, 1, 3)
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit.setMaxLength(32)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 1, 1, 3)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_29.setEnabled(False)
        self.lineEdit_29.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_29.setFont(font)
        self.lineEdit_29.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_29.setMaxLength(64)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout_3.addWidget(self.lineEdit_29, 6, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_2.setMaxLength(32)
        self.lineEdit_2.setClearButtonEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 1, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 3, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.gridLayout_3.addWidget(self.radioButton_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 5, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_8.setMaxLength(512)
        self.lineEdit_8.setClearButtonEnabled(False)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_4.addWidget(self.lineEdit_8, 1, 2, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(10, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 10, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_13.setEnabled(False)
        self.lineEdit_13.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_13.setMaxLength(1024)
        self.lineEdit_13.setClearButtonEnabled(False)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_4.addWidget(self.lineEdit_13, 15, 2, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 6, 4, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_12.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_12.setMaxLength(128)
        self.lineEdit_12.setClearButtonEnabled(False)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_4.addWidget(self.lineEdit_12, 10, 2, 1, 3)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_14.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_14.setMaxLength(128)
        self.lineEdit_14.setClearButtonEnabled(False)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_4.addWidget(self.lineEdit_14, 16, 2, 1, 3)
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_4.addWidget(self.checkBox_3, 11, 3, 1, 1)
        self.radioButton_8 = QtWidgets.QRadioButton(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.radioButton_8.setFont(font)
        self.radioButton_8.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radioButton_8.setChecked(True)
        self.radioButton_8.setObjectName("radioButton_8")
        self.buttonGroup_4 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_4.setObjectName("buttonGroup_4")
        self.buttonGroup_4.addButton(self.radioButton_8)
        self.gridLayout_4.addWidget(self.radioButton_8, 9, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_4.addWidget(self.checkBox_2, 11, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 15, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setMouseTracking(False)
        self.lineEdit_9.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_9.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lineEdit_9.setAcceptDrops(False)
        self.lineEdit_9.setMaxLength(10)
        self.lineEdit_9.setReadOnly(False)
        self.lineEdit_9.setClearButtonEnabled(False)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_4.addWidget(self.lineEdit_9, 2, 2, 1, 3)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_11.setMaxLength(128)
        self.lineEdit_11.setClearButtonEnabled(False)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_4.addWidget(self.lineEdit_11, 5, 2, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 3, 0, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setObjectName("radioButton_6")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.radioButton_6)
        self.gridLayout_4.addWidget(self.radioButton_6, 6, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tab_2)
        self.label_43.setStyleSheet("color: red;")
        self.label_43.setObjectName("label_43")
        self.gridLayout_4.addWidget(self.label_43, 4, 2, 1, 3)
        self.checkBox = QtWidgets.QCheckBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_4.addWidget(self.checkBox, 8, 2, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 2, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_7.setMaxLength(32)
        self.lineEdit_7.setClearButtonEnabled(False)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_4.addWidget(self.lineEdit_7, 0, 2, 1, 3)
        self.radioButton_7 = QtWidgets.QRadioButton(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.radioButton_7.setFont(font)
        self.radioButton_7.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radioButton_7.setObjectName("radioButton_7")
        self.buttonGroup_3.addButton(self.radioButton_7)
        self.gridLayout_4.addWidget(self.radioButton_7, 6, 3, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setMouseTracking(False)
        self.lineEdit_10.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_10.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lineEdit_10.setAcceptDrops(False)
        self.lineEdit_10.setMaxLength(10)
        self.lineEdit_10.setReadOnly(False)
        self.lineEdit_10.setClearButtonEnabled(False)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_4.addWidget(self.lineEdit_10, 3, 2, 1, 3)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 16, 0, 1, 1)
        self.radioButton_9 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_9.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.radioButton_9.setFont(font)
        self.radioButton_9.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radioButton_9.setObjectName("radioButton_9")
        self.buttonGroup_4.addButton(self.radioButton_9)
        self.gridLayout_4.addWidget(self.radioButton_9, 14, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.line_5 = QtWidgets.QFrame(self.tab_3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_5.addWidget(self.line_5, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab_3)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.comboBox.setMaxVisibleItems(5)
        self.comboBox.setMaxCount(5)
        self.comboBox.setModelColumn(0)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_5.addWidget(self.comboBox, 4, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: red;")
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_44 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.gridLayout_5.addWidget(self.label_44, 3, 0, 1, 1)
        self.toolBox = QtWidgets.QToolBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.toolBox.setFont(font)
        self.toolBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 718, 162))
        self.page.setObjectName("page")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_12 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 0, 0, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_15.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_15.setMaxLength(512)
        self.lineEdit_15.setClearButtonEnabled(False)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_6.addWidget(self.lineEdit_15, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 3, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 399, 119))
        self.page_2.setObjectName("page_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_15 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 0, 0, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_16.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_16.setMaxLength(512)
        self.lineEdit_16.setClearButtonEnabled(False)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_7.addWidget(self.lineEdit_16, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 3, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 718, 180))
        self.page_3.setObjectName("page_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setMinimumSize(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_2.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget_2.setUsesScrollButtons(True)
        self.tabWidget_2.setDocumentMode(False)
        self.tabWidget_2.setTabsClosable(True)
        self.tabWidget_2.setMovable(False)
        self.tabWidget_2.setTabBarAutoHide(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_34 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_18.addWidget(self.label_34, 0, 2, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_24.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_24.setFont(font)
        self.lineEdit_24.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_24.setMaxLength(64)
        self.lineEdit_24.setClearButtonEnabled(False)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_18.addWidget(self.lineEdit_24, 1, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_18.addWidget(self.label_33, 0, 1, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_23.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_23.setFont(font)
        self.lineEdit_23.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_23.setMaxLength(256)
        self.lineEdit_23.setClearButtonEnabled(False)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_18.addWidget(self.lineEdit_23, 3, 0, 1, 3)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_22.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_22.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_22.setFont(font)
        self.lineEdit_22.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_22.setMaxLength(64)
        self.lineEdit_22.setClearButtonEnabled(False)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_18.addWidget(self.lineEdit_22, 1, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.tab_5)
        self.spinBox_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spinBox_2.setMinimum(1917)
        self.spinBox_2.setMaximum(2060)
        self.spinBox_2.setProperty("value", 2020)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_18.addWidget(self.spinBox_2, 1, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout_18.addWidget(self.label_35, 2, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_18.addWidget(self.label_32, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.gridLayout_8.addWidget(self.tabWidget_2, 1, 0, 1, 1)
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 402, 119))
        self.page_4.setObjectName("page_4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_18 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_9.addWidget(self.label_18, 0, 0, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_17.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_17.setMaxLength(512)
        self.lineEdit_17.setClearButtonEnabled(False)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_9.addWidget(self.lineEdit_17, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_9.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_9.addWidget(self.label_20, 3, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_4, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 718, 180))
        self.page_5.setObjectName("page_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_3.sizePolicy().hasHeightForWidth())
        self.tabWidget_3.setSizePolicy(sizePolicy)
        self.tabWidget_3.setMinimumSize(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setTabsClosable(True)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_32.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_32.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_32.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_32.setMaxLength(32)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout_19.addWidget(self.lineEdit_32, 1, 0, 1, 2)
        self.label_38 = QtWidgets.QLabel(self.tab_6)
        self.label_38.setObjectName("label_38")
        self.gridLayout_19.addWidget(self.label_38, 2, 1, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_30.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_30.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_30.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_30.setMaxLength(64)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout_19.addWidget(self.lineEdit_30, 3, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab_6)
        self.label_36.setObjectName("label_36")
        self.gridLayout_19.addWidget(self.label_36, 0, 0, 1, 2)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_31.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_31.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_31.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_31.setMaxLength(64)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout_19.addWidget(self.lineEdit_31, 3, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.tab_6)
        self.label_37.setObjectName("label_37")
        self.gridLayout_19.addWidget(self.label_37, 2, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_6, "")
        self.gridLayout_10.addWidget(self.tabWidget_3, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_5, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 330, 119))
        self.page_6.setObjectName("page_6")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_21 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_11.addWidget(self.label_21, 0, 0, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_18.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_18.setFont(font)
        self.lineEdit_18.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_18.setMaxLength(512)
        self.lineEdit_18.setClearButtonEnabled(False)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_11.addWidget(self.lineEdit_18, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_11.addWidget(self.label_22, 2, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_11.addWidget(self.label_23, 3, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_6, "")
        self.gridLayout_5.addWidget(self.toolBox, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_29 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_17.addWidget(self.label_29, 2, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_17.addWidget(self.checkBox_4, 5, 0, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setMinimumSize(QtCore.QSize(0, 50))
        self.textEdit_2.setMaximumSize(QtCore.QSize(16777214, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_17.addWidget(self.textEdit_2, 3, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_19.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_19.setFont(font)
        self.lineEdit_19.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_19.setMaxLength(128)
        self.lineEdit_19.setClearButtonEnabled(False)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_16.addWidget(self.lineEdit_19, 1, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_16.addWidget(self.label_28, 2, 0, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_20.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_20.setFont(font)
        self.lineEdit_20.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_20.setMaxLength(128)
        self.lineEdit_20.setClearButtonEnabled(False)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_16.addWidget(self.lineEdit_20, 1, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_16.addWidget(self.label_27, 0, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_16.addWidget(self.label_25, 0, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_16.addWidget(self.label_26, 0, 1, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_21.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_21.setFont(font)
        self.lineEdit_21.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_21.setMaxLength(128)
        self.lineEdit_21.setClearButtonEnabled(False)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_16.addWidget(self.lineEdit_21, 1, 2, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_28.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_28.setFont(font)
        self.lineEdit_28.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_28.setMaxLength(1024)
        self.lineEdit_28.setClearButtonEnabled(False)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_16.addWidget(self.lineEdit_28, 3, 0, 1, 3)
        self.gridLayout_17.addWidget(self.groupBox, 0, 0, 1, 1)
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_3.sizePolicy().hasHeightForWidth())
        self.textEdit_3.setSizePolicy(sizePolicy)
        self.textEdit_3.setMinimumSize(QtCore.QSize(0, 50))
        self.textEdit_3.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textEdit_3.setObjectName("textEdit_3")
        self.gridLayout_17.addWidget(self.textEdit_3, 7, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_17.addWidget(self.label_31, 8, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_4)
        self.label_30.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_17.addWidget(self.label_30, 6, 0, 1, 1)
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_4.sizePolicy().hasHeightForWidth())
        self.textEdit_4.setSizePolicy(sizePolicy)
        self.textEdit_4.setMinimumSize(QtCore.QSize(0, 50))
        self.textEdit_4.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.textEdit_4.setObjectName("textEdit_4")
        self.gridLayout_17.addWidget(self.textEdit_4, 9, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_20.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setEnabled(False)
        self.line.setGeometry(QtCore.QRect(48, 97, 41, 16))
        self.line.setStyleSheet("color: rgb(255, 0, 0);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(4)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setEnabled(False)
        self.line_2.setGeometry(QtCore.QRect(177, 97, 41, 16))
        self.line_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(4)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setEnabled(False)
        self.line_3.setGeometry(QtCore.QRect(319, 97, 41, 16))
        self.line_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(4)
        self.line_3.setMidLineWidth(0)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setEnabled(False)
        self.line_4.setGeometry(QtCore.QRect(448, 97, 41, 16))
        self.line_4.setStyleSheet("color: rgb(255, 0, 0);")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(4)
        self.line_4.setMidLineWidth(0)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.line_2.raise_()
        self.line.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.tabWidget.raise_()
        self.widget_2.raise_()
        self.widget_header.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addSeparator()
        self.menu.addAction(self.action_4)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Генератор xml-файлов для партий СИ"))
        self.label_39.setText(_translate("MainWindow", "Всего СИ в партии"))
        self.label_40.setText(_translate("MainWindow", "Поверок в одном файле"))
        self.pushButton.setText(_translate("MainWindow", "Создать xml-файл"))
        self.label_41.setText(_translate("MainWindow", "Максимально 500000 записей"))
        self.label_42.setText(_translate("MainWindow", "Максимально 5000 записей"))
        self.radioButton_4.setText(_translate("MainWindow", "Заводской № *"))
        self.lineEdit_25.setPlaceholderText(_translate("MainWindow", "Конец номера после изменяемой части"))
        self.lineEdit_27.setPlaceholderText(_translate("MainWindow", "Изменяемая часть номера *"))
        self.radioButton_5.setText(_translate("MainWindow", "Буквенно-цифровое обозначение *"))
        self.lineEdit_26.setPlaceholderText(_translate("MainWindow", "Конец номера после изменяемой части"))
        self.spinBox.setSpecialValueText(_translate("MainWindow", "-"))
        self.radioButton_3.setText(_translate("MainWindow", "Наименование СИ, поступ. в экспл. до 01.06.1993 *"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Начало номера до изменяемой части"))
        self.label_3.setText(_translate("MainWindow", "Год выпуска"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "Начало номера до изменяемой части"))
        self.radioButton.setText(_translate("MainWindow", "Тип СИ в реестре ФИФ ОЕИ *"))
        self.lineEdit_29.setPlaceholderText(_translate("MainWindow", "Изменяемая часть номера *"))
        self.label_2.setText(_translate("MainWindow", "Модификация *"))
        self.radioButton_2.setText(_translate("MainWindow", "Наименование СИ (ГОСТ 8.326-78) *"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Сведения о СИ"))
        self.label_7.setText(_translate("MainWindow", "Документ на методику поверки *"))
        self.label_9.setText(_translate("MainWindow", "     Номер наклейки"))
        self.label.setText(_translate("MainWindow", "Условный шифр знака поверки *"))
        self.checkBox_3.setText(_translate("MainWindow", "Знак поверки на СИ"))
        self.radioButton_8.setText(_translate("MainWindow", "Пригодно"))
        self.checkBox_2.setText(_translate("MainWindow", "Знак поверки в паспорте"))
        self.label_10.setText(_translate("MainWindow", "     Причина непригодности"))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "ДД.ММ.ГГГГ"))
        self.label_8.setText(_translate("MainWindow", "Тип поверки"))
        self.label_6.setText(_translate("MainWindow", "Действительна до"))
        self.radioButton_6.setText(_translate("MainWindow", "Первичная"))
        self.label_4.setText(_translate("MainWindow", "Владелец СИ *"))
        self.label_43.setText(_translate("MainWindow", "Даты не могут быть одинаковыми"))
        self.checkBox.setText(_translate("MainWindow", "Использование результатов калибровки"))
        self.label_5.setText(_translate("MainWindow", "Дата поверки *"))
        self.radioButton_7.setText(_translate("MainWindow", "Периодическая"))
        self.lineEdit_10.setPlaceholderText(_translate("MainWindow", "ДД.ММ.ГГГГ"))
        self.label_11.setText(_translate("MainWindow", "ФИО поверителя"))
        self.radioButton_9.setText(_translate("MainWindow", "Непригодно"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Сведения о поверке"))
        self.comboBox.setItemText(1, _translate("MainWindow", "поверка имитационным методом"))
        self.comboBox.setItemText(2, _translate("MainWindow", "самоповерка"))
        self.comboBox.setItemText(3, _translate("MainWindow", "поверка расчетным методом"))
        self.comboBox.setItemText(4, _translate("MainWindow", "поверка с использованием первичной референтной методики измерений"))
        self.label_24.setText(_translate("MainWindow", "Необходимо заполнить хотя бы одно поле"))
        self.label_44.setText(_translate("MainWindow", "Методы поверки без применения средств поверки"))
        self.label_12.setText(_translate("MainWindow", "№ ГПЭ по реестру"))
        self.label_13.setText(_translate("MainWindow", "Значения перечисляются подряд и разделяются \";\""))
        self.label_14.setText(_translate("MainWindow", "Пример: гэт000-2011;гэт001-2018;гэт002-77 "))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Государственный первичный эталон"))
        self.label_15.setText(_translate("MainWindow", "№ эталона по реестру"))
        self.label_16.setText(_translate("MainWindow", "Значения перечисляются подряд и разделяются \";\""))
        self.label_17.setText(_translate("MainWindow", "Пример: 3.2.ХХХ.0001.2018;3.2.ХХХ.0004.2015;3.2.ХХХ.0005.2019"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Эталон единицы величины"))
        self.label_34.setText(_translate("MainWindow", "Заводской №/№ партии"))
        self.label_33.setText(_translate("MainWindow", "Год выпуска *"))
        self.label_35.setText(_translate("MainWindow", "Метрологические характеристики СО"))
        self.label_32.setText(_translate("MainWindow", "№ типа СО по реестру *"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Образец"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Стандартные образцы, применяемые при поверке"))
        self.label_18.setText(_translate("MainWindow", "№ СИ по перечню"))
        self.label_19.setText(_translate("MainWindow", "Значения перечисляются подряд и разделяются \";\""))
        self.label_20.setText(_translate("MainWindow", "Пример: 10597.86.5Р.00024;10457.86.2Р.00034;10597.86.0Р.00023"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "СИ, применяемое в качестве эталона"))
        self.label_38.setText(_translate("MainWindow", "Буквенно-цифровое обозначение *"))
        self.label_36.setText(_translate("MainWindow", "Регистрационный № типа СИ *"))
        self.label_37.setText(_translate("MainWindow", "Заводской номер *"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "СИ"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", "СИ, применяемые при поверке"))
        self.label_21.setText(_translate("MainWindow", "Наименование, № по перечню"))
        self.label_22.setText(_translate("MainWindow", "Значения перечисляются подряд и разделяются \";\""))
        self.label_23.setText(_translate("MainWindow", "Пример: ДРГ.1;РКТ.10"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("MainWindow", "Вещество (материал), применяемое при поверке"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Средства поверки"))
        self.label_29.setText(_translate("MainWindow", "Состав СИ, представленного на поверку"))
        self.checkBox_4.setText(_translate("MainWindow", "Поверка в сокращенном объеме"))
        self.groupBox.setTitle(_translate("MainWindow", "Условия проведения поверки"))
        self.label_28.setText(_translate("MainWindow", "Другие факторы"))
        self.label_27.setText(_translate("MainWindow", "Относительная влажность, % *"))
        self.label_25.setText(_translate("MainWindow", "Температура, °C *"))
        self.label_26.setText(_translate("MainWindow", "Атмосферное давление, кПа *"))
        self.label_31.setText(_translate("MainWindow", "Прочие сведения"))
        self.label_30.setText(_translate("MainWindow", "Краткая характеристика объема поверки"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Прочие сведения"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.action.setText(_translate("MainWindow", "Инструкция"))
        self.action_2.setText(_translate("MainWindow", "О программе"))
        self.action_4.setText(_translate("MainWindow", "Выход"))

import res_rc
